name: Deploy production
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_NAME_PROD }}
          audience: ${{ secrets.WORKLOAD_IDENTITY_AUDIENCE_PROD }}
      - name: Deploy to Google Cloud Run
        env:
          ENVIRONMENT: production
          GIT_USERNAME: ${{ secrets.USER_GITHUB }}
          GIT_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SERVICE_NAME: ${{ vars.SERVICE_NAME }}
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID_PROD }}
          GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
        run: python3 scripts/deploy.py
