name: Pull Request CI
on:
  pull_request:
    branches:
      - develop
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Install module requirements
        run: |
          echo "https://${{ secrets.USER_GITHUB }}:${{secrets.TOKEN_GITHUB}}@github.com" > ~/.git-credentials
          git config --global credential.helper store
          go mod download
      - name: Build code
        run: go build -v ./...
      - name: Run unit tests
        run: go test -cover -v ./...
